---
# Based on:
# https://docs.snips.ai/articles/raspberrypi/manual-setup

- name: Adds apt key
  apt_key:
    keyserver: gpg.mozilla.org
    id: D4F50CDCA10A2849

# TODO: Remove replace when https://github.com/snipsco/snips-issues/issues/161 is fixed
- name: Adds apt repository
  apt_repository:
      repo: "deb https://raspbian.snips.ai/{{ ansible_distribution_release | replace('buster', 'stretch') }} stable main"
      state: present

- name: Adds Debian arm key
  apt_key:
    url: https://ftp-master.debian.org/keys/release-10.asc

- name: Adds apt repository
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster non-free"
    state: present

# TODO: Remove libatlas3 when https://github.com/snipsco/snips-issues/issues/161 is fixed
- name: Install required packages
  apt:
    name:
      # snips-platform-voice except mosquitto
      - libgfortran3
      - 'libatlas3-base=3.10.3-8+rpi1'
      - snips-analytics
      - snips-asr
      - snips-audio-server
      - snips-dialogue
      - snips-hotword
      - snips-queries
      - snips-tts
      - snips-template
      - snips-skill-server
    state: present
    update_cache: true

- name: Setup devices
  copy:
    src: asound.conf
    dest: /etc/asound.conf

- name: Setup MQTT
  lineinfile:
    path: /etc/snips.toml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^mqtt = "
      line: "mqtt = {{ snips_mqtt_server }}"
    - regexp: "^mqtt_username = "
      line: "mqtt_username = {{ snips_mqtt_username }}"
    - regexp: "^mqtt_password = "
      line: "mqtt_password = {{ snips_mqtt_password }}"
  no_log: true

# NOTE: Only runs when update_assistant is passed and snips_assistant_url is defined
- include_tasks: update-assistant.yml
  when: snips_assistant_url
  tags:
    - never
    - update_assistant

- include_tasks: install-personal-wakeword.yml
  when: snips_personal_wakeword_install
